### ISSUE TITLE
could you show more detail about how to use two demos?

### ISSUE THREAD

**Issue by zychen2016** [quolc/neural-collage#3]
Hi!
First, type your code
`python3 demo_spatial_translation.py --config ./configs/sn_projection_dog_and_cat_256_scbn.yml --gen_model ./sn_projection_dog_and_cat_256/ResNetGenerator_450000.npz --gpu 0`
![image](https://user-images.githubusercontent.com/23021461/49932566-540eac80-ff04-11e8-88ca-63363ca7b043.png)

 Then, I use GPU clusters, so that I only can open  browser use  command line.
For example, 
`user@user:opera`,
Then X11 will open.
![image](https://user-images.githubusercontent.com/23021461/49932509-275a9500-ff04-11e8-934a-69fc7e317090.png)
But how to load image in that page?
Thanks.

**Comment by zychen2016** [comment]
could you show me more about how to use the demo?
Mouse pressed the button,but could'nt load the image.

**Comment by quolc** [comment]
Sorry for late reply.

If the script was correctly loaded, class names (e.g., Chihuahua) will appear in the select box under "Select base class".
<img width="855" alt="2018-12-17 15 56 14" src="https://user-images.githubusercontent.com/46786/50071242-68102200-0214-11e9-883d-13c0e46156d6.png">

Then images can be generated by pushing the "Generate" button after selecting a desired class.

<img width="831" alt="2018-12-17 15 56 50" src="https://user-images.githubusercontent.com/46786/50071245-6a727c00-0214-11e9-8b7d-e174c883b32a.png">

I suspect that the js of demo does not work correctly in your environment.
Please could you provide the error messages shown in your browser's js (developer) console?
