### ISSUE TITLE
测试

### ISSUE THREAD

**Issue by Jiangzl** [quolc/neural-collage#4]
你好，在我运行  python demo_spatial_translation.py  --config ./configs/sn_projection_dog_and_cat_256_scbn.yml  --gen_model ./sn_projection_dog_and_cat_256/ResNetGenerator_450000.npz --gpu 0  之后，程序运行出现了卡顿，一直再没有输出也没有下一步的显示，控制台如下，请问你是否知道是什么原因？
![1](https://user-images.githubusercontent.com/8221918/50469554-eeccb800-09e7-11e9-9fa0-64dd104ecf86.png)

**Comment by quolc** [comment]
@Jiangzl sorry for limited explanation about how to run the demo.
It seems that the script is correctly running in your environment.
After starting the script, open http://localhost:5000/ using a browser on the same machine.

**Comment by Jiangzl** [comment]
好的，可以正常使用了，非常感谢！
