### ISSUE TITLE
runtime error in google colab notebook

### ISSUE THREAD

**Issue by ghost** [quolc/neural-collage#7]
RuntimeError                              Traceback (most recent call last)
<ipython-input-3-68eb4b63afff> in <module>()
      1 import chainer
----> 2 chainer.cuda.get_device(0).use()

/usr/local/lib/python3.6/dist-packages/chainer/backends/cuda.py in get_device(*args)
    224     warnings.warn('get_device is deprecated. Please use get_device_from_id or'
    225                   ' get_device_from_array instead.', DeprecationWarning)
--> 226     return _get_device(*args)
    227 
    228 

/usr/local/lib/python3.6/dist-packages/chainer/backends/cuda.py in _get_device(*args)
    230     for arg in args:
    231         if type(arg) is not bool and isinstance(arg, _integer_types):
--> 232             check_cuda_available()
    233             return Device(arg)
    234         if isinstance(arg, ndarray):

/usr/local/lib/python3.6/dist-packages/chainer/backends/cuda.py in check_cuda_available()
     91                '(see https://github.com/chainer/chainer#installation).')
     92         msg += str(_resolution_error)
---> 93         raise RuntimeError(msg)
     94     if (not cudnn_enabled and
     95             not _cudnn_disabled_by_user and

RuntimeError: CUDA environment is not correctly set up
(see https://github.com/chainer/chainer#installation).CuPy is not correctly installed.

If you are using wheel distribution (cupy-cudaXX), make sure that the version of CuPy you installed matches with the version of CUDA on your host.
Also, confirm that only one CuPy package is installed:
  $ pip freeze

If you are building CuPy from source, please check your environment, uninstall CuPy and reinstall it with:
  $ pip install cupy --no-cache-dir -vvvv

Check the Installation Guide for details:
  https://docs-cupy.chainer.org/en/latest/install.html

original error: libcublas.so.9.2: cannot open shared object file: No such file or directory

get this error in the google colab notebook

**Comment by quolc** [comment]
Thank you for reporting the issue!
The error was caused because of the change of the Colab environment.
We have replaced the setup code to support the new CUDA version (c83bdb2).
